<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * hcv_reservationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hcv_reservationsRepository extends EntityRepository
{
}
